### ISSUE TITLE
`run_escape` module not found

### ISSUE THREAD

**Issue by Yijia-Xiao** [DavideBuffelli/SizeShiftReg#2]
Hi,

Thank you for the great work. I am trying to use the work for further research, however, I encountered errors when running the demo. It seems that some package in `lib` folder is missing (`from lib.run_escape import names, run_escape`).

Error message: `ModuleNotFoundError: No module named 'lib.runescape'`.

Thanks!

**Comment by DavideBuffelli** [comment]
Hi, thank you very much for letting me know. I have now [added the file](https://github.com/DavideBuffelli/SizeShiftReg/commit/78afa66b217d658c66ed9083ec236b6b1497a3d5). Please let me know if the problem persist.

**Comment by Yijia-Xiao** [comment]
Hi @DavideBuffelli,

The problem has been solved. Thank you very much!

Best
